################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
software/src \
software/config \
software/build/obj \
software/boards/bms \
software/.metadata/.plugins/org.eclipse.cdt.make.core \
ChibiOS/testhal/common/testbuild \
ChibiOS/testhal/STM32L1xx/UART \
ChibiOS/testhal/STM32L1xx/SPI \
ChibiOS/testhal/STM32L1xx/PWM-ICU \
ChibiOS/testhal/STM32L1xx/IRQ_STORM \
ChibiOS/testhal/STM32L1xx/EXT \
ChibiOS/testhal/STM32L1xx/ADC \
ChibiOS/testhal/STM32F4xx/USB_CDC \
ChibiOS/testhal/STM32F4xx/UART \
ChibiOS/testhal/STM32F4xx/SPI \
ChibiOS/testhal/STM32F4xx/SDC \
ChibiOS/testhal/STM32F4xx/RTC_FATTIME \
ChibiOS/testhal/STM32F4xx/RTC \
ChibiOS/testhal/STM32F4xx/PWM-ICU \
ChibiOS/testhal/STM32F4xx/IRQ_STORM_FPU \
ChibiOS/testhal/STM32F4xx/IRQ_STORM \
ChibiOS/testhal/STM32F4xx/I2C \
ChibiOS/testhal/STM32F4xx/GPT \
ChibiOS/testhal/STM32F4xx/EXT \
ChibiOS/testhal/STM32F4xx/DMA_STORM \
ChibiOS/testhal/STM32F4xx/DAC \
ChibiOS/testhal/STM32F4xx/CAN \
ChibiOS/testhal/STM32F4xx/ADC \
ChibiOS/testhal/STM32F37x/USB_CDC \
ChibiOS/testhal/STM32F37x/UART \
ChibiOS/testhal/STM32F37x/SPI \
ChibiOS/testhal/STM32F37x/SDADC \
ChibiOS/testhal/STM32F37x/PWM-ICU \
ChibiOS/testhal/STM32F37x/IRQ_STORM \
ChibiOS/testhal/STM32F37x/I2C \
ChibiOS/testhal/STM32F37x/EXT \
ChibiOS/testhal/STM32F37x/CAN \
ChibiOS/testhal/STM32F37x/ADC \
ChibiOS/testhal/STM32F30x/USB_CDC \
ChibiOS/testhal/STM32F30x/UART \
ChibiOS/testhal/STM32F30x/SPI \
ChibiOS/testhal/STM32F30x/PWM-ICU \
ChibiOS/testhal/STM32F30x/IRQ_STORM \
ChibiOS/testhal/STM32F30x/EXT \
ChibiOS/testhal/STM32F30x/CAN \
ChibiOS/testhal/STM32F30x/ADC_DUAL \
ChibiOS/testhal/STM32F30x/ADC \
ChibiOS/testhal/STM32F1xx/USB_CDC_F107 \
ChibiOS/testhal/STM32F1xx/USB_CDC \
ChibiOS/testhal/STM32F1xx/UART \
ChibiOS/testhal/STM32F1xx/SPI \
ChibiOS/testhal/STM32F1xx/SDC \
ChibiOS/testhal/STM32F1xx/RTC_FATTIME \
ChibiOS/testhal/STM32F1xx/RTC \
ChibiOS/testhal/STM32F1xx/PWM-ICU \
ChibiOS/testhal/STM32F1xx/IRQ_STORM \
ChibiOS/testhal/STM32F1xx/I2C \
ChibiOS/testhal/STM32F1xx/GPT \
ChibiOS/testhal/STM32F1xx/EXT \
ChibiOS/testhal/STM32F1xx/CAN \
ChibiOS/testhal/STM32F1xx/ADC \
ChibiOS/testhal/STM32F0xx/UART \
ChibiOS/testhal/STM32F0xx/SPI \
ChibiOS/testhal/STM32F0xx/PWM-ICU \
ChibiOS/testhal/STM32F0xx/IRQ_STORM \
ChibiOS/testhal/STM32F0xx/EXT \
ChibiOS/testhal/STM32F0xx/ADC \
ChibiOS/testhal/SPC56ELxx/PWM-ICU \
ChibiOS/testhal/SPC563Mxx/ADC \
ChibiOS/testhal/SPC560Pxx/PWM-ICU \
ChibiOS/testhal/LPC13xx/IRQ_STORM \
ChibiOS/testhal/LPC122x/IRQ_STORM \
ChibiOS/testhal/LPC11xx/IRQ_STORM \
ChibiOS/test \
ChibiOS/test/coverage \
ChibiOS/os/various \
ChibiOS/os/various/lwip_bindings \
ChibiOS/os/various/lwip_bindings/arch \
ChibiOS/os/various/fatfs_bindings \
ChibiOS/os/various/devices_lib/accel \
ChibiOS/os/ports/common/ARMCMx \
ChibiOS/os/ports/RVCT/ARMCMx \
ChibiOS/os/ports/IAR/ARMCMx \
ChibiOS/os/ports/GCC/SIMIA32 \
ChibiOS/os/ports/GCC/PPC \
ChibiOS/os/ports/GCC/AVR \
ChibiOS/os/ports/GCC/ARMCMx \
ChibiOS/os/ports/GCC/ARMCMx/STM32L1xx \
ChibiOS/os/ports/GCC/ARMCMx/STM32F4xx \
ChibiOS/os/ports/GCC/ARMCMx/STM32F3xx \
ChibiOS/os/ports/GCC/ARMCMx/STM32F2xx \
ChibiOS/os/ports/GCC/ARMCMx/STM32F1xx \
ChibiOS/os/ports/GCC/ARMCMx/STM32F0xx \
ChibiOS/os/ports/GCC/ARMCMx/SAM4L \
ChibiOS/os/ports/GCC/ARMCMx/LPC8xx \
ChibiOS/os/ports/GCC/ARMCMx/LPC13xx \
ChibiOS/os/ports/GCC/ARMCMx/LPC122x \
ChibiOS/os/ports/GCC/ARMCMx/LPC11xx \
ChibiOS/os/ports/GCC/ARM \
ChibiOS/os/kernel/templates \
ChibiOS/os/kernel/src \
ChibiOS/os/hal/templates \
ChibiOS/os/hal/templates/meta \
ChibiOS/os/hal/src \
ChibiOS/os/hal/platforms/Win32 \
ChibiOS/os/hal/platforms/STM32L1xx \
ChibiOS/os/hal/platforms/STM32F4xx \
ChibiOS/os/hal/platforms/STM32F37x \
ChibiOS/os/hal/platforms/STM32F30x \
ChibiOS/os/hal/platforms/STM32F1xx \
ChibiOS/os/hal/platforms/STM32F0xx \
ChibiOS/os/hal/platforms/STM32 \
ChibiOS/os/hal/platforms/STM32/USBv1 \
ChibiOS/os/hal/platforms/STM32/USARTv2 \
ChibiOS/os/hal/platforms/STM32/USARTv1 \
ChibiOS/os/hal/platforms/STM32/SPIv2 \
ChibiOS/os/hal/platforms/STM32/SPIv1 \
ChibiOS/os/hal/platforms/STM32/RTCv2 \
ChibiOS/os/hal/platforms/STM32/RTCv1 \
ChibiOS/os/hal/platforms/STM32/OTGv1 \
ChibiOS/os/hal/platforms/STM32/I2Cv2 \
ChibiOS/os/hal/platforms/STM32/I2Cv1 \
ChibiOS/os/hal/platforms/STM32/GPIOv2 \
ChibiOS/os/hal/platforms/STM32/GPIOv1 \
ChibiOS/os/hal/platforms/STM32/DACv1 \
ChibiOS/os/hal/platforms/SPC5xx/eTimer_v1 \
ChibiOS/os/hal/platforms/SPC5xx/SIU_v1 \
ChibiOS/os/hal/platforms/SPC5xx/SIUL_v1 \
ChibiOS/os/hal/platforms/SPC5xx/LINFlex_v1 \
ChibiOS/os/hal/platforms/SPC5xx/FlexPWM_v1 \
ChibiOS/os/hal/platforms/SPC5xx/ESCI_v1 \
ChibiOS/os/hal/platforms/SPC5xx/EQADC_v1 \
ChibiOS/os/hal/platforms/SPC5xx/EDMA_v1 \
ChibiOS/os/hal/platforms/SPC56ELxx \
ChibiOS/os/hal/platforms/SPC564Axx \
ChibiOS/os/hal/platforms/SPC563Mxx \
ChibiOS/os/hal/platforms/SPC560Pxx \
ChibiOS/os/hal/platforms/SPC560BCxx \
ChibiOS/os/hal/platforms/Posix \
ChibiOS/os/hal/platforms/MSP430 \
ChibiOS/os/hal/platforms/LPC8xx \
ChibiOS/os/hal/platforms/LPC214x \
ChibiOS/os/hal/platforms/LPC13xx \
ChibiOS/os/hal/platforms/LPC122x \
ChibiOS/os/hal/platforms/LPC11xx \
ChibiOS/os/hal/platforms/LPC11Uxx \
ChibiOS/os/hal/platforms/AVR \
ChibiOS/os/hal/platforms/AT91SAM7 \
ChibiOS/os/hal/platforms/AT91SAM7/at91lib \
ChibiOS/demos/Win32-MinGW \
ChibiOS/demos/Posix-GCC \
ChibiOS/demos/PPC-SPC56EL-GCC \
ChibiOS/demos/PPC-SPC564A-GCC \
ChibiOS/demos/PPC-SPC563M-GCC \
ChibiOS/demos/PPC-SPC560P-GCC \
ChibiOS/demos/PPC-SPC560B-GCC \
ChibiOS/demos/MSP430-MSP430x1611-GCC \
ChibiOS/demos/AVR-ArduinoMega-GCC \
ChibiOS/demos/AVR-ATmega128-GCC \
ChibiOS/demos/AVR-AT90CANx-GCC \
ChibiOS/demos/ARMCM4-STM32F407-LWIP-FATFS-USB/web \
ChibiOS/demos/ARMCM4-STM32F407-LWIP-FATFS-USB \
ChibiOS/demos/ARMCM4-STM32F407-LWIP/web \
ChibiOS/demos/ARMCM4-STM32F407-LWIP \
ChibiOS/demos/ARMCM4-STM32F407-DISCOVERY-MEMS \
ChibiOS/demos/ARMCM4-STM32F407-DISCOVERY \
ChibiOS/demos/ARMCM4-STM32F373-STM32373C_EVAL \
ChibiOS/demos/ARMCM4-STM32F303-DISCOVERY \
ChibiOS/demos/ARMCM3-STM32L152-DISCOVERY \
ChibiOS/demos/ARMCM3-STM32F107-LWIP/web \
ChibiOS/demos/ARMCM3-STM32F107-LWIP \
ChibiOS/demos/ARMCM3-STM32F107-FATFS \
ChibiOS/demos/ARMCM3-STM32F107 \
ChibiOS/demos/ARMCM3-STM32F103ZG-FATFS \
ChibiOS/demos/ARMCM3-STM32F103-FATFS \
ChibiOS/demos/ARMCM3-STM32F103 \
ChibiOS/demos/ARMCM3-STM32F100-DISCOVERY \
ChibiOS/demos/ARMCM3-LPC1343-OLIMEX \
ChibiOS/demos/ARMCM3-LPC1343-LPCXPRESSO \
ChibiOS/demos/ARMCM3-GENERIC-KERNEL \
ChibiOS/demos/ARMCM0P-LPC812-LPCXPRESSO \
ChibiOS/demos/ARMCM0-STM32F051-DISCOVERY \
ChibiOS/demos/ARMCM0-LPC11U14-LPCXPRESSO \
ChibiOS/demos/ARMCM0-LPC1114-LPCXPRESSO \
ChibiOS/demos/ARM7-LPC214x-GCC \
ChibiOS/demos/ARM7-LPC214x-FATFS-GCC \
ChibiOS/demos/ARM7-AT91SAM7X-UIP-GCC/web \
ChibiOS/demos/ARM7-AT91SAM7X-UIP-GCC \
ChibiOS/demos/ARM7-AT91SAM7X-LWIP-GCC/web \
ChibiOS/demos/ARM7-AT91SAM7X-LWIP-GCC \
ChibiOS/demos/ARM7-AT91SAM7X-GCC \
ChibiOS/demos/ARM7-AT91SAM7X-FATFS-GCC \
ChibiOS/boards/simulator \
ChibiOS/boards/ST_STM32VL_DISCOVERY \
ChibiOS/boards/ST_STM32L_DISCOVERY \
ChibiOS/boards/ST_STM32F4_DISCOVERY \
ChibiOS/boards/ST_STM32F3_DISCOVERY \
ChibiOS/boards/ST_STM32F0_DISCOVERY \
ChibiOS/boards/ST_STM32373C_EVAL \
ChibiOS/boards/ST_STM3220G_EVAL \
ChibiOS/boards/ST_STM3210E_EVAL \
ChibiOS/boards/ST_STM3210C_EVAL \
ChibiOS/boards/ST_EVB_SPC56EL \
ChibiOS/boards/ST_EVB_SPC564A \
ChibiOS/boards/ST_EVB_SPC563M \
ChibiOS/boards/ST_EVB_SPC560P \
ChibiOS/boards/ST_EVB_SPC560BC \
ChibiOS/boards/STUDIEL_AT91SAM7A3_EK \
ChibiOS/boards/OLIMEX_STM32_P407 \
ChibiOS/boards/OLIMEX_STM32_P107 \
ChibiOS/boards/OLIMEX_STM32_P103 \
ChibiOS/boards/OLIMEX_STM32_LCD \
ChibiOS/boards/OLIMEX_STM32_H103 \
ChibiOS/boards/OLIMEX_STM32_E407 \
ChibiOS/boards/OLIMEX_STM32_103STK \
ChibiOS/boards/OLIMEX_SAM7_P256 \
ChibiOS/boards/OLIMEX_SAM7_EX256 \
ChibiOS/boards/OLIMEX_MSP430_P1611 \
ChibiOS/boards/OLIMEX_LPC_P2148 \
ChibiOS/boards/OLIMEX_LPC_P1343 \
ChibiOS/boards/OLIMEX_LPC-P1227 \
ChibiOS/boards/OLIMEX_AVR_MT_128 \
ChibiOS/boards/OLIMEX_AVR_CAN \
ChibiOS/boards/NONSTANDARD_STM32F4_BARTHESS1 \
ChibiOS/boards/NGX_BB_LPC11U14 \
ChibiOS/boards/MAPLEMINI_STM32_F103 \
ChibiOS/boards/EA_LPCXPRESSO_LPC812 \
ChibiOS/boards/EA_LPCXPRESSO_BB_1343 \
ChibiOS/boards/EA_LPCXPRESSO_BB_11U14 \
ChibiOS/boards/EA_LPCXPRESSO_BB_1114 \
ChibiOS/boards/ARDUINO_MEGA \

